// Generated by CodiumAI
import { convertToDecimalPriceUSD } from '../prices'

describe('convertToDecimalPriceUSD', () => {
  // Should return a string with the USD currency symbol and the price decimalized and fixed to two decimal places
  it('should return a string with the USD currency symbol and the price decimalized and fixed to two decimal places', () => {
    // Arrange
    const price = 12500

    // Act
    const result = convertToDecimalPriceUSD(price)

    // Assert
    expect(result).toBe('$125.00')
  })

  // Should correctly convert a price in cents to a decimal price in USD
  it('should correctly convert a price in cents to a decimal price in USD', () => {
    // Arrange
    const testCases = [
      { input: 12500, expected: '$125.00' },
      { input: 100, expected: '$1.00' },
      { input: 99999, expected: '$999.99' },
      { input: 350, expected: '$3.50' },
    ]

    // Act & Assert
    testCases.forEach((testCase) => {
      const result = convertToDecimalPriceUSD(testCase.input)
      expect(result).toBe(testCase.expected)
    })
  })

  // Should handle zero cents and return "$0.00"
  it('should handle zero cents and return "$0.00"', () => {
    // Arrange
    const price = 0

    // Act
    const result = convertToDecimalPriceUSD(price)

    // Assert
    expect(result).toBe('$0.00')
  })
})
